description: Genius API
links:
- href: https://api.genius.com
  rel: self
title: Genius API
properties:
  meta:
    - "$ref": "#/definitions/meta"
  data:
    type: object
    anyOf:
    - "$ref": "#/definitions/annotation"
