description: Genius API
links:
- href: https://api.genius.com
  rel: self
title: Genius API
definitions:
  meta:
    title: meta
    description: FIXME meta
    type: object
    definitions:
      status:
        type:
        - integer
      message:
        type:
        - string
  response:
    title: response
    description: FIXME response
properties:
  meta:
    "$ref": "#/definitions/meta"
  response:
    type: object
    anyOf:
    - "$ref": "#/definitions/annotation"
